from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

from src.data.csv_schemas import CSV_SCHEMAS, REQUIRED_V1_FILES
from src.services.historical_replay_contract_service import (
    HISTORICAL_REPLAY_TEMPLATE_HEADERS,
)
from src.services.public_source_import_service import PUBLIC_SOURCE_TEMPLATE_HEADERS

DEFAULT_TEMPLATE_ROOT = Path(__file__).resolve().parents[2] / "templates" / "real_data_inputs"

VETERAN_TEMPLATE_HEADERS: dict[str, tuple[str, ...]] = {
    "veteran_player_inputs.csv": (
        "season",
        "snapshot_date",
        "player_id",
        "player_name",
        "position",
        "nfl_team",
        "age",
        "team_id",
        "team_name",
        "league_rank",
        "is_league_rank_top5",
        "source_snapshot_id",
        "source_name",
        "source_date",
        "data_quality_tier",
    ),
    "veteran_feature_registry.csv": (
        "position",
        "feature_name",
        "feature_category",
        "parent_component",
        "default_weight",
        "min_weight",
        "max_weight",
        "evidence_strength",
        "expected_direction",
        "lve_importance",
        "coefficient_policy",
        "scoring_status",
        "is_core",
        "missing_data_penalty",
        "requires_source_type",
        "confidence_impact",
        "risk_flag_hint",
        "upside_flag_hint",
        "floor_flag_hint",
        "failure_modes",
        "source_summary",
        "implementation_notes",
    ),
    "veteran_feature_scores.csv": (
        "season",
        "snapshot_date",
        "player_id",
        "position",
        "feature_name",
        "normalized_score",
        "source_key",
        "source_confidence",
        "is_missing",
        "missing_reason",
        "is_user_override",
        "override_reason",
    ),
    "veteran_source_catalog.csv": (
        "source_key",
        "source_name",
        "source_type",
        "source_family",
        "source_domain",
        "authority_tier",
        "priority_rank",
        "required_for_modes",
        "freshness_window_hours",
        "source_format",
        "local_path",
        "source_url",
        "source_path_or_url",
        "source_date",
        "retrieved_at",
        "captured_at_local",
        "effective_date",
        "season",
        "scoring_context",
        "checksum_sha256",
        "parser_version",
        "source_notes",
        "is_active",
        "reliability_score",
        "notes",
    ),
    "veteran_audit_notes.csv": (
        "note_id",
        "season",
        "player_id",
        "feature_name",
        "note_scope",
        "note_text",
        "source_key",
        "affects_score",
        "created_at",
    ),
    "veteran_manual_overrides.csv": (
        "override_id",
        "season",
        "player_id",
        "position",
        "feature_name",
        "target_field",
        "old_value",
        "override_value",
        "override_type",
        "reason_code",
        "source_key",
        "override_reason",
        "provenance",
        "requested_by",
        "approved_by",
        "self_approved",
        "review_status",
        "status",
        "created_at",
    ),
}

ROOKIE_TEMPLATE_HEADERS: dict[str, tuple[str, ...]] = {
    "rookie_prospect_inputs.csv": (
        "player_id",
        "player_name",
        "position",
        "class_year",
        "model_mode",
        "source_snapshot_id",
        "source_name",
        "source_date",
        "data_completeness_status",
        "draft_capital",
        "rushing_profile",
        "passing_efficiency",
        "sack_avoidance",
        "age_trajectory",
        "workload_earning",
        "rush_efficiency",
        "receiving_impact",
        "goal_line_power",
        "target_earning",
        "efficiency_dominance",
        "chain_moving",
        "receiving_efficiency",
        "route_role",
        "production_volume",
        "athletic_size",
        "rookie_opportunity_score",
    ),
    "rookie_raw_metrics.csv": (
        "player_id",
        "player_name",
        "position",
        "class_year",
        "model_mode",
        "source_snapshot_id",
        "source_name",
        "source_date",
        "data_completeness_status",
        "overall_pick",
        "age_on_sept_1",
        "rush_yards_per_game",
        "adjusted_yards_per_attempt",
        "pressure_to_sack_rate",
        "team_touch_share",
        "yards_after_contact_per_attempt",
        "receiving_yards_per_route",
        "goal_line_share",
        "target_share",
        "yards_per_route_run",
        "first_downs_per_route",
        "route_participation",
        "receiving_yards_share",
        "speed_score",
        "rookie_opportunity_score",
    ),
    "rookie_normalization_rules.csv": (
        "rule_id",
        "position",
        "feature_name",
        "raw_metric",
        "transform_type",
        "direction",
        "min_raw",
        "max_raw",
        "anchor_low",
        "anchor_high",
        "missing_policy",
        "source_snapshot_id",
        "notes",
    ),
    "veteran_opportunity_assets.csv": (
        "asset_id",
        "asset_name",
        "asset_type",
        "position",
        "availability_status",
        "role_tier",
        "lve_veteran_score",
        "win_now_score",
        "hold_value_score",
        "trade_liquidity_score",
        "source_snapshot_id",
        "source_date",
        "is_active_benchmark",
        "notes",
    ),
}

NFLVERSE_STATS_UPGRADE_TEMPLATE_HEADERS: dict[str, tuple[str, ...]] = {
    "nflverse_player_stats_weekly.csv": (
        "season",
        "week",
        "player_id",
        "gsis_id",
        "sleeper_id",
        "player_name",
        "position",
        "team",
        "passing_yards",
        "passing_tds",
        "interceptions",
        "rushing_attempts",
        "rushing_yards",
        "rushing_tds",
        "rushing_first_downs",
        "targets",
        "receptions",
        "receiving_yards",
        "receiving_tds",
        "receiving_first_downs",
        "passing_first_downs",
        "passing_epa",
        "rushing_epa",
        "receiving_epa",
        "receiving_air_yards",
        "target_share",
        "air_yards_share",
        "wopr",
        "return_yards",
        "return_tds",
        "kick_return_yards",
        "kick_return_tds",
        "punt_return_yards",
        "punt_return_tds",
        "fumbles_lost",
        "source_updated_at",
    ),
    "nflverse_snap_counts_weekly.csv": (
        "season",
        "week",
        "game_id",
        "gsis_id",
        "sleeper_id",
        "player_name",
        "position",
        "team",
        "opponent",
        "offense_snaps",
        "offense_pct",
        "st_snaps",
        "st_pct",
        "source_updated_at",
    ),
    "nflverse_participation_player_weekly.csv": (
        "season",
        "week",
        "team",
        "gsis_id",
        "sleeper_id",
        "player_name",
        "position",
        "offensive_plays_on_field",
        "team_offensive_plays",
        "dropbacks_on_field",
        "team_dropbacks",
        "route_participation_proxy",
        "targets",
        "targets_per_dropback_snap_proxy",
        "red_zone_on_field",
        "short_yardage_on_field",
        "confidence",
    ),
    "nflverse_depth_chart_weekly.csv": (
        "season",
        "week",
        "team",
        "dt",
        "gsis_id",
        "espn_id",
        "sleeper_id",
        "player_name",
        "position",
        "pos_slot",
        "pos_rank",
        "depth_chart_role_score",
        "schema_version",
    ),
    "nflverse_injuries_weekly.csv": (
        "season",
        "week",
        "team",
        "gsis_id",
        "sleeper_id",
        "player_name",
        "position",
        "report_primary_injury",
        "report_secondary_injury",
        "report_status",
        "practice_primary_injury",
        "practice_secondary_injury",
        "practice_status",
        "normalized_body_part",
        "date_modified",
        "source_confidence",
    ),
    "nflverse_identity_map.csv": (
        "sleeper_id",
        "gsis_id",
        "nfl_id",
        "espn_id",
        "fantasy_data_id",
        "pfr_id",
        "player_id",
        "player_name",
        "normalized_name",
        "position",
        "team",
        "match_method",
        "match_confidence",
        "review_status",
        "notes",
    ),
    "projection_raw_import.csv": (
        "season",
        "week",
        "projection_scope",
        "projection_source_status",
        "source_id",
        "source_player_id",
        "sleeper_id",
        "gsis_id",
        "player_name",
        "position",
        "team",
        "projected_games",
        "projected_starts",
        "projected_passing_yards",
        "projected_passing_tds",
        "projected_interceptions",
        "projected_rushing_attempts",
        "projected_rushing_yards",
        "projected_rushing_tds",
        "projected_targets",
        "projected_receptions",
        "projected_receiving_yards",
        "projected_receiving_tds",
        "projected_rushing_first_downs",
        "projected_receiving_first_downs",
        "projected_fumbles_lost",
        "source_projected_points",
        "source_scoring_format",
        "source_updated_at",
        "imported_at",
        "confidence",
    ),
    "lve_opportunity_weekly.csv": (
        "season",
        "week",
        "player_id",
        "gsis_id",
        "sleeper_id",
        "player_name",
        "position",
        "team",
        "source_xfp",
        "lve_xfp",
        "lve_actual",
        "opportunity_delta",
        "rush_attempts",
        "targets",
        "expected_receptions",
        "expected_rush_yards",
        "expected_rec_yards",
        "expected_pass_yards",
        "expected_rush_tds",
        "expected_rec_tds",
        "expected_pass_tds",
        "expected_rush_first_downs",
        "expected_rec_first_downs",
        "red_zone_opportunities",
        "goal_line_opportunities",
        "short_yardage_opportunities",
        "lve_weighted_opportunities",
        "td_dependency",
        "source_model_version",
        "source_updated_at",
        "confidence",
    ),
    "lve_normalized_veteran_features.csv": (
        "season",
        "as_of_week",
        "player_id",
        "gsis_id",
        "sleeper_id",
        "player_name",
        "position",
        "team",
        "weighted_recent_lve_ppg_score",
        "expected_lve_points_score",
        "lve_projection_value",
        "projection_source_status",
        "role_security",
        "workload_earning",
        "target_earning_stability",
        "route_role",
        "efficiency_score",
        "first_down_td_fit",
        "age_curve",
        "age_raw",
        "age_bucket",
        "age_warning",
        "age_source_status",
        "age_interaction_flags",
        "injury_durability",
        "private_stat_value",
        "market_liquidity",
        "confidence",
        "missing_data_penalty",
        "warnings",
        "source_version",
        "computed_at",
    ),
    "lve_normalized_feature_receipts.csv": (
        "season",
        "as_of_week",
        "player_id",
        "gsis_id",
        "sleeper_id",
        "player_name",
        "position",
        "team",
        "feature_bucket",
        "feature_name",
        "raw_value",
        "normalized_value",
        "normalized_score",
        "source_key",
        "source_status",
        "projection_source_status",
        "source_field",
        "warning_status",
        "warning_reason",
        "imputed_flag",
        "is_missing",
        "imputation_value",
        "model_usage",
        "computed_at",
    ),
}


@dataclass(frozen=True)
class RealInputTemplateIssue:
    template_group: str
    file_name: str
    issue: str


def expected_template_headers() -> dict[str, dict[str, tuple[str, ...]]]:
    return {
        "data_pack": {
            file_name: CSV_SCHEMAS[file_name].all_columns for file_name in REQUIRED_V1_FILES
        },
        "veteran_model": VETERAN_TEMPLATE_HEADERS,
        "rookie_model": ROOKIE_TEMPLATE_HEADERS,
        "historical_replay": HISTORICAL_REPLAY_TEMPLATE_HEADERS,
        "public_sources": PUBLIC_SOURCE_TEMPLATE_HEADERS,
        "nflverse_stats_upgrade": NFLVERSE_STATS_UPGRADE_TEMPLATE_HEADERS,
    }


def validate_real_input_templates(
    template_root: str | Path = DEFAULT_TEMPLATE_ROOT,
) -> tuple[RealInputTemplateIssue, ...]:
    root = Path(template_root)
    issues: list[RealInputTemplateIssue] = []
    for group_name, files in expected_template_headers().items():
        for file_name, expected_header in files.items():
            path = root / group_name / file_name
            if not path.exists():
                issues.append(
                    RealInputTemplateIssue(group_name, file_name, "Template file is missing.")
                )
                continue
            actual_header = _csv_header(path)
            if actual_header != expected_header:
                issues.append(
                    RealInputTemplateIssue(
                        group_name,
                        file_name,
                        "Template header does not match the runtime schema.",
                    )
                )
    return tuple(issues)


def _csv_header(path: Path) -> tuple[str, ...]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.reader(handle)
        return tuple(next(reader, ()))



