"""Research-only Trading Lab contracts and validators."""

from src.trading_lab.schema_registry import (
    ALLOWED_STATUS_BY_ARTIFACT,
    CORE_ARTIFACT_TYPES,
    PROHIBITED_FIELD_NAMES,
    SCHEMA_REGISTRY,
    ArtifactSchema,
    prohibited_field_names_in,
    schema_for_artifact,
)
from src.trading_lab.source_inventory import (
    ALLOWED_SOURCE_CATEGORIES,
    ALLOWED_SOURCE_USES,
    MANUAL_ARTIFACT_REQUIRED_FIELDS,
    MANUAL_REVIEW_PACKET_REQUIRED_SECTIONS,
    PAPER_JOURNAL_REQUIRED_FIELDS,
    PROHIBITED_SOURCE_CATEGORIES,
    PaperJournalEntry,
    ResearchSourceMetadata,
    ValidationIssue,
    WatchlistNote,
    assert_valid_source_metadata,
    validate_artifact_text_fields,
    validate_manual_artifact_payload,
    validate_manual_review_packet,
    validate_paper_journal_entry,
    validate_research_config,
    validate_source_metadata,
    validate_watchlist_note,
)

__all__ = [
    "ALLOWED_SOURCE_CATEGORIES",
    "ALLOWED_SOURCE_USES",
    "ALLOWED_STATUS_BY_ARTIFACT",
    "CORE_ARTIFACT_TYPES",
    "MANUAL_REVIEW_PACKET_REQUIRED_SECTIONS",
    "MANUAL_ARTIFACT_REQUIRED_FIELDS",
    "PAPER_JOURNAL_REQUIRED_FIELDS",
    "PROHIBITED_FIELD_NAMES",
    "PROHIBITED_SOURCE_CATEGORIES",
    "SCHEMA_REGISTRY",
    "ArtifactSchema",
    "PaperJournalEntry",
    "ResearchSourceMetadata",
    "ValidationIssue",
    "WatchlistNote",
    "assert_valid_source_metadata",
    "prohibited_field_names_in",
    "schema_for_artifact",
    "validate_artifact_text_fields",
    "validate_manual_artifact_payload",
    "validate_manual_review_packet",
    "validate_paper_journal_entry",
    "validate_research_config",
    "validate_source_metadata",
    "validate_watchlist_note",
]
